Repository codezoned/PsipherFrontend, pull requests merged in 2020-07, with the labels that each got.

#3 HLD of Psipher
  HLD.md
  PsipherComplete.png
  PsipherSwagger.png
  README.md
Labels: documentation

#4 Added Login, Signup and other related for user registeration
  .gitignore
  amplify/.config/project-config.json
  amplify/backend/auth/psipher/parameters.json
  amplify/backend/auth/psipher/psipher-cloudformation-template.yml
  amplify/backend/backend-config.json
  amplify/team-provider-info.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/App.js
  src/components/styled/EmailConfirmFormWrapper.js
  src/components/styled/FormWrapper.js
  src/components/styled/FullWidthWrapper.js
  src/containers/ConfirmEmailContainer.js
  src/containers/DashboardContainer.js
  src/containers/ForgotPasswordContainer.js
  src/containers/LoginContainer.js
  src/containers/PasswordResetContainer.js
  src/containers/SignUpContainer.js
  src/global.js
  src/index.css
  src/index.js
  src/routes/PrivateRoutes.js
  src/routes/PublicRoutes.js
  src/themes/Colors.js
  src/utils/constants.js
  src/utils/helpers.js
  yarn.lock
Labels: enhancement

#6 Removed Amplify
  amplify/.config/project-config.json
  amplify/backend/auth/psipher/parameters.json
  amplify/backend/auth/psipher/psipher-cloudformation-template.yml
  amplify/backend/backend-config.json
  amplify/team-provider-info.json
  src/aws-exports.js
Labels: dependencies
